### ISSUE TITLE
[chore] ios, android 앱 이름 수정

### ISSUE THREAD

**Issue by eunddodi** [depromeet/ahmatda-app#9]

**Comment by hyesungoh** [comment]
이거 ... 아직 안됐나 ?!

**Comment by eunddodi** [comment]
> 이거 ... 아직 안됐나 ?!

지금 거의 다했어

**Comment by eunddodi** [comment]
> 이거 ... 아직 안됐나 ?!

아 이거 그 프로젝트 자체 이름이랑 ios android 패키지 이름이랑 다른거같던데???

**Comment by hyesungoh** [comment]
그러게 나도 했었는데 배포 할 때 다시 확인해봐야할듯

**Comment by eunddodi** [comment]
> 그러게 나도 했었는데 배포 할 때 다시 확인해봐야할듯

오잉 일단 PR 올려볼게
